/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

/**
 *
 * @author Pc
 */
public class panelDatos extends javax.swing.JPanel {

    /**
     * Creates new form DatosPersonales
     */
    public panelDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();

        lblNombre.setText("nombre");

        lblCI.setText("CI");

        lblCorreo.setText("correo");

        lblCarrera.setText("carrera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCorreo)
                        .addComponent(lblNombre)
                        .addComponent(lblCI))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarrera)
                        .addGap(8, 8, 8)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombre)
                .addGap(27, 27, 27)
                .addComponent(lblCI)
                .addGap(31, 31, 31)
                .addComponent(lblCorreo)
                .addGap(32, 32, 32)
                .addComponent(lblCarrera)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
