/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import com.google.zxing.*;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import java.nio.file.*;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.client.j2se.MatrixToImageWriter;

import conexionbd.conexion;  // Importa tu clase de conexión

public class pasoQR extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pasoQR.class.getName());

    /**
     * Creates new form pasoQR
     */
    public pasoQR() {
        initComponents();
        cargarPagos();
    }
    
    private void cargarPagos(){
    DefaultTableModel modelo = (DefaultTableModel) tablaPagos.getModel();
    modelo.setRowCount(0); // limpiar tabla

    try(Connection con = conexion.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM pago")){
        while(rs.next()){
            modelo.addRow(new Object[]{
                rs.getInt("id_pago"),
                rs.getString("nombre_cliente"),
                rs.getDouble("monto"),
                rs.getString("estado")
            });
        }
    } catch(SQLException e){
        e.printStackTrace();
    }
}

private void generarQR(int id, String nombre, double monto){
    String datos = "id_pago="+id+"\nNombre:"+nombre+"\nMonto:"+monto;
    try{
        QRCodeWriter qr = new QRCodeWriter();
        BitMatrix bm = qr.encode(datos, BarcodeFormat.QR_CODE, 200, 200);
        Path path = Path.of("pagoQR.png");
        MatrixToImageWriter.writeToPath(bm, "PNG", path);
        lblQR.setIcon(new ImageIcon(path.toAbsolutePath().toString()));
        JOptionPane.showMessageDialog(this, "QR generado para el pago ID "+id);
    } catch(Exception e){
        e.printStackTrace();
    }
}

private void validarPago(int id){
    try(Connection con = conexion.getConnection();
        PreparedStatement ps = con.prepareStatement("UPDATE pago SET estado='PAGADO' WHERE id_pago=?")){
        ps.setInt(1, id);
        int res = ps.executeUpdate();
        if(res>0){
            JOptionPane.showMessageDialog(this, "Pago ID "+id+" validado correctamente.");
        }
    } catch(SQLException e){
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTabla = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        panelAcciones = new javax.swing.JPanel();
        btnValidarPago = new javax.swing.JButton();
        lblQR = new javax.swing.JLabel();
        btnGenerarQR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        scrollTabla.setViewportView(jScrollPane1);

        btnValidarPago.setText("Validar pago");
        btnValidarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarPagoActionPerformed(evt);
            }
        });

        lblQR.setPreferredSize(new java.awt.Dimension(200, 400));

        btnGenerarQR.setText("Generar QR");
        btnGenerarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccionesLayout.createSequentialGroup()
                        .addComponent(btnGenerarQR)
                        .addGap(159, 159, 159)
                        .addComponent(btnValidarPago)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccionesLayout.createSequentialGroup()
                        .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccionesLayout.createSequentialGroup()
                .addComponent(lblQR, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidarPago)
                    .addComponent(btnGenerarQR))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarQRActionPerformed
        // TODO add your handling code here:
        int fila = tablaPagos.getSelectedRow();
        if(fila != -1){
            int idPago = Integer.parseInt(tablaPagos.getValueAt(fila, 0).toString());
            String nombre = tablaPagos.getValueAt(fila, 1).toString();
            double monto = Double.parseDouble(tablaPagos.getValueAt(fila,2).toString());
            generarQR(idPago, nombre, monto);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un pago de la tabla.");
        }
    }//GEN-LAST:event_btnGenerarQRActionPerformed

    private void btnValidarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarPagoActionPerformed
        // TODO add your handling code here:
        int fila = tablaPagos.getSelectedRow();
        if(fila != -1){
               int idPago = Integer.parseInt(tablaPagos.getValueAt(fila, 0).toString());
                validarPago(idPago);
                cargarPagos(); // refrescar tabla
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un pago de la tabla.");
        }
    }//GEN-LAST:event_btnValidarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pasoQR().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarQR;
    private javax.swing.JButton btnValidarPago;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQR;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaPagos;
    // End of variables declaration//GEN-END:variables
}
